# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FunFood' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'SwiftyJSON'

  # Pods for FunFood

  target 'FunFoodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FunFoodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
